### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by egillespie** [egillespie/codelab-ruby-laptop-setup#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://shrouded-scrubland-5966.herokuapp.com/) and meets the following [project](http://lansingcodelab.com/lessons/ruby-laptop-setup/1) criteria:

- [x] be in a GitHub repo (since you're getting the app from Heroku, you'll have to go to the project folder, then remove their origin with `git remote rm origin`, and finally once again add the correct GitHub repo with `git remote add origin https://github.com/YOUR-USERNAME/codelab-ruby-laptop-setup.git`)
- [x] be hosted on Heroku

## Add'l Notes

I got this error (again) when running `bundle install`:

```
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
```

Luckily I figured this out way back when we were talking about this library on Slack. The following command got the gem to install correctly. I'm mostly putting it here for posterity and my own records, since it seems I get this error any time `bundle` tries to update `pg`.

```
sudo env ARCHFLAGS="-arch x86_64" gem install pg -v '0.17.1' -- --with-pg-config=/Applications/Postgres.app/Contents/Versions/9.4/bin/pg_config
```

**Comment by chrisvfritz** [comment]
:shipit: Looks good! You shouldn't actually need to `bundle install` for this project (since students aren't expected to have PostgreSQL installed by this point), but I see it _is_ listed in the project steps. I'll override them for this lesson to avoid people encountering an error! Thanks. :smiley:
